# -*- coding: utf-8 -*-
"""Magic

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qQKZ_3HmMyKL8_raTem2rfCSRilceoCH
"""

import pandas as pd
import matplotlib.pyplot as plt

isRunning = False
data = pd.read_csv("data.csv")

while isRunning == False:
    print("------------------------------------")
    print("welcome in our data-analyse terminal")
    print("1. most expencive prices")
    print("2. new products")
    print("3. high quantity products")
    print("------------------------------------")
    print("")

    #user interface
    UI = input("Made a decison: ")

    if UI == "1":
        # top 10 prices
        exPrice = data[['Product', 'Price']].head(10)
        print(exPrice)


    elif UI == "2":
        # new sale of products
        df = pd.DataFrame(data)
        newDateTopTen = df[(data['SaleDate'] > '2022-01-05')]
        print(newDateTopTen)

    elif UI == "3":
        df = pd.DataFrame(data)
        QuantityProducts = df[df['Quantity'] > 25]
        QuantityProducts.plot(kind='bar', x='Product', y='Quantity', legend=False)
        plt.title('Products with Quantity > 25')
        plt.xlabel('Product')
        plt.ylabel('Quantity')
        plt.show()

